name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libcppunit-dev

      - name: Build library
        run: make -C src

      - name: Build tests
        run: |
          PATH=$PWD/src:$PATH make -C src/tests setup all
          PATH=$PWD/src:$PATH make -C demo/tests setup all

      - name: Run tests
        working-directory: demo/tests
        run: ./http_server_test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cppunit-report
          path: demo/tests/cppunit-report.xml

      - name: Test Report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: CppUnit Tests
          path: demo/tests/cppunit-report.xml
          reporter: junit
