name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libcppunit-dev

      - name: Build library
        run: make -C src

      - name: Run tests
        run: |
          PATH=$PWD/src:$PATH make -C src/tests
          PATH=$PWD/src:$PATH make -C demo/tests
